#!/bin/bash
# Puget Systems — Team LLM Initialization
# Detects GPUs, recommends a model, writes .env, launches the stack.

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}============================================================${NC}"
echo -e "${BLUE}   Puget Systems — Team LLM Setup (vLLM)${NC}"
echo -e "${BLUE}============================================================${NC}"

# --- GPU Detection ---
echo ""
echo -e "${YELLOW}[1/3] Detecting GPUs...${NC}"

if ! command -v nvidia-smi &> /dev/null; then
    echo -e "${RED}✗ nvidia-smi not found. NVIDIA drivers required.${NC}"
    exit 1
fi

GPU_COUNT=$(nvidia-smi --query-gpu=count --format=csv,noheader | head -1)
GPU_NAME=$(nvidia-smi --query-gpu=gpu_name --format=csv,noheader | head -1)
VRAM_MB=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits | head -1)
VRAM_GB=$((VRAM_MB / 1024))
TOTAL_VRAM=$((VRAM_GB * GPU_COUNT))

echo -e "${GREEN}✓ Found ${GPU_COUNT}x ${GPU_NAME} (${VRAM_GB} GB each, ${TOTAL_VRAM} GB total)${NC}"

# --- Cache Proxy Status ---
if [ -f .env ]; then
    source .env 2>/dev/null
fi

if [ -n "$CACHE_PROXY" ]; then
    echo -e "${GREEN}✓ Cache Proxy: $CACHE_PROXY${NC}"
else
    echo -e "${YELLOW}⚠ No cache proxy configured (downloads go direct).${NC}"
    echo "  To enable, add CACHE_PROXY=http://<ip>:3128 to .env"
fi

# --- Model Selection ---
echo ""
echo -e "${YELLOW}[2/3] Select a model${NC}"
echo ""
echo "  Available models (based on ${TOTAL_VRAM} GB total VRAM):"
echo ""

# Always available
echo "  vLLM loads models in full precision (BF16) by default."
echo "  Quantized (AWQ) options are available for larger models."
echo ""
echo "  1) Qwen 3 8B            - Fast, single GPU (~16 GB BF16)"
echo "  2) Qwen 3 32B           - Best quality (~64 GB BF16, needs multi-GPU)"

# Conditional on VRAM
if [ "$TOTAL_VRAM" -ge 40 ]; then
    echo "  3) DeepSeek R1 70B AWQ  - Flagship reasoning (~38 GB quantized) [Recommended]"
else
    echo -e "  3) DeepSeek R1 70B AWQ  - ${RED}Requires ~38 GB (you have ${TOTAL_VRAM} GB)${NC}"
fi

echo "  4) Custom               - Enter a HuggingFace model ID"
echo "  5) Exit"
echo ""
read -p "Select [1-5]: " CHOICE

MODEL_ID=""
PARALLEL=$GPU_COUNT
case $CHOICE in
    1) MODEL_ID="Qwen/Qwen3-8B"; PARALLEL=1 ;;
    2) MODEL_ID="Qwen/Qwen3-32B" ;;
    3) MODEL_ID="Valdemardi/DeepSeek-R1-Distill-Llama-70B-AWQ" ;;
    4) read -p "  Enter HuggingFace model ID: " MODEL_ID ;;
    *) echo "Exiting."; exit 0 ;;
esac

if [ -z "$MODEL_ID" ]; then
    echo -e "${RED}No model selected.${NC}"
    exit 1
fi

# --- Write Config ---
echo ""
echo -e "${YELLOW}[3/3] Writing configuration...${NC}"

# Write or update .env
cat > .env <<EOF
# Puget Systems — Team LLM Configuration
# Generated by init.sh on $(date)

# Model to serve (HuggingFace model ID)
MODEL_ID=${MODEL_ID}

# Number of GPUs for tensor parallelism
GPU_COUNT=${PARALLEL}

# Maximum context length (tokens)
MAX_CONTEXT=32768

# Cache proxy (optional, for faster model downloads)
# CACHE_PROXY=http://<ip>:3128
EOF

# Preserve cache proxy if it was set
if [ -n "$CACHE_PROXY" ]; then
    sed -i "s|# CACHE_PROXY=.*|CACHE_PROXY=${CACHE_PROXY}|" .env
fi

echo -e "${GREEN}✓ Configuration written to .env${NC}"
echo ""
echo "  Model:    $MODEL_ID"
echo "  GPUs:     $PARALLEL"
echo "  Context:  32768 tokens"
echo ""

read -p "Start the stack now? (Y/n): " START
if [[ "$START" != "n" && "$START" != "N" ]]; then
    echo -e "${BLUE}Starting vLLM server (first run downloads the model, this may take a while)...${NC}"
    docker compose up -d
    echo ""
    echo -e "${GREEN}✓ Stack starting.${NC}"
    echo -e "  Monitor model download:  ${BLUE}docker compose logs -f inference${NC}"
    echo -e "  Chat UI (after ready):   ${BLUE}http://localhost:3000${NC}"
    echo -e "  API endpoint:            ${BLUE}http://localhost:8000/v1${NC}"
else
    echo "Run 'docker compose up -d' when ready."
fi
