#!/bin/bash
# Puget Systems — Team LLM Initialization
# Detects GPUs, recommends a model, writes .env, launches the stack.

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}============================================================${NC}"
echo -e "${BLUE}   Puget Systems — Team LLM Setup (vLLM)${NC}"
echo -e "${BLUE}============================================================${NC}"

# --- GPU Detection ---
echo ""
echo -e "${YELLOW}[1/3] Detecting GPUs...${NC}"

if ! command -v nvidia-smi &> /dev/null; then
    echo -e "${RED}✗ nvidia-smi not found. NVIDIA drivers required.${NC}"
    exit 1
fi

GPU_COUNT=$(nvidia-smi --query-gpu=count --format=csv,noheader | head -1)
GPU_NAME=$(nvidia-smi --query-gpu=gpu_name --format=csv,noheader | head -1)
VRAM_MB=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits | head -1)
VRAM_GB=$((VRAM_MB / 1024))
TOTAL_VRAM=$((VRAM_GB * GPU_COUNT))

echo -e "${GREEN}✓ Found ${GPU_COUNT}x ${GPU_NAME} (${VRAM_GB} GB each, ${TOTAL_VRAM} GB total)${NC}"

# --- Cache Proxy Status ---
if [ -f .env ]; then
    source .env 2>/dev/null
fi

if [ -n "$CACHE_PROXY" ]; then
    echo -e "${GREEN}✓ Cache Proxy: $CACHE_PROXY${NC}"
else
    echo -e "${YELLOW}⚠ No cache proxy configured (downloads go direct).${NC}"
    echo "  To enable, add CACHE_PROXY=http://<ip>:3128 to .env"
fi

# --- Model Selection ---
echo ""
echo -e "${YELLOW}[2/3] Select a model${NC}"
echo ""
echo "  Available models (based on ${TOTAL_VRAM} GB total VRAM):"
echo ""

# Always available
echo "  vLLM loads models in full precision (BF16) by default."
echo "  Quantized (AWQ) options are available for larger models."
echo ""
echo "  1) Qwen 3 8B            - Fast, single GPU (~16 GB BF16)"
echo "  2) Qwen 3 32B           - Best quality (~64 GB BF16, needs multi-GPU)"

# Conditional on VRAM
if [ "$TOTAL_VRAM" -ge 40 ]; then
    echo "  3) DeepSeek R1 70B AWQ  - Flagship reasoning (~38 GB quantized) [Recommended]"
else
    echo -e "  3) DeepSeek R1 70B AWQ  - ${RED}Requires ~38 GB (you have ${TOTAL_VRAM} GB)${NC}"
fi

echo "  4) Custom               - Enter a HuggingFace model ID"
echo "  5) Exit"
echo ""
read -p "Select [1-5]: " CHOICE

MODEL_ID=""
PARALLEL=$GPU_COUNT
case $CHOICE in
    1) MODEL_ID="Qwen/Qwen3-8B"; PARALLEL=1 ;;
    2) MODEL_ID="Qwen/Qwen3-32B" ;;
    3) MODEL_ID="Valdemardi/DeepSeek-R1-Distill-Llama-70B-AWQ" ;;
    4) read -p "  Enter HuggingFace model ID: " MODEL_ID ;;
    *) echo "Exiting."; exit 0 ;;
esac

if [ -z "$MODEL_ID" ]; then
    echo -e "${RED}No model selected.${NC}"
    exit 1
fi

# --- Write Config ---
echo ""
echo -e "${YELLOW}[3/3] Writing configuration...${NC}"

# Write or update .env
cat > .env <<EOF
# Puget Systems — Team LLM Configuration
# Generated by init.sh on $(date)

# Model to serve (HuggingFace model ID)
MODEL_ID=${MODEL_ID}

# Number of GPUs for tensor parallelism
GPU_COUNT=${PARALLEL}

# Maximum context length (tokens)
MAX_CONTEXT=32768

# Cache proxy (optional, for faster model downloads)
# CACHE_PROXY=http://<ip>:3128
EOF

# Preserve cache proxy if it was set
if [ -n "$CACHE_PROXY" ]; then
    sed -i "s|# CACHE_PROXY=.*|CACHE_PROXY=${CACHE_PROXY}|" .env
fi

echo -e "${GREEN}✓ Configuration written to .env${NC}"
echo ""
echo "  Model:    $MODEL_ID"
echo "  GPUs:     $PARALLEL"
echo "  Context:  32768 tokens"
echo ""

read -p "Start the stack now? (Y/n): " START
if [[ "$START" != "n" && "$START" != "N" ]]; then
    echo -e "${BLUE}Starting vLLM server...${NC}"
    docker compose up -d
    echo ""
    
    LOCAL_IP=$(hostname -I | awk '{print $1}')
    echo -e "${GREEN}✓ Stack starting.${NC}"
    echo -e "  Chat UI:  ${BLUE}http://localhost:3000${NC}"
    echo -e "  API:      ${BLUE}http://localhost:8000/v1${NC}"
    echo -e "  Network:  ${BLUE}http://${LOCAL_IP}:3000${NC}"
    echo ""
    
    echo -e "${YELLOW}Waiting for model to download and load...${NC}"
    echo "  (This may take 5-30 minutes depending on model size and bandwidth)"
    echo ""
    
    CONTAINER_NAME="puget_vllm"
    # Convert model ID to HF cache directory format (org/model -> models--org--model)
    HF_CACHE_DIR="models--$(echo "$MODEL_ID" | sed 's|/|--|g')"
    HF_CACHE_ROOT="/root/.cache/huggingface"
    READY=false
    LAST_PHASE=""
    PHASE_LEVEL=0           # Monotonic: phases only advance forward
    LAST_RESTART_COUNT=0    # Track container restarts to detect crash loops
    CRASH_DETECTIONS=0      # Number of times we've seen a restart increment
    
    while ! $READY; do
        # Check if container is still running
        if ! docker ps --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
            echo -e "\n${RED}✗ vLLM container exited. Check logs:${NC}"
            echo -e "  ${BLUE}docker compose logs inference${NC}"
            break
        fi
        
        # Detect crash loops (container restarting repeatedly)
        RESTART_COUNT=$(docker inspect --format='{{.RestartCount}}' "$CONTAINER_NAME" 2>/dev/null || echo "0")
        if [ "$RESTART_COUNT" -gt "$LAST_RESTART_COUNT" ] 2>/dev/null; then
            CRASH_DETECTIONS=$((CRASH_DETECTIONS + 1))
            LAST_RESTART_COUNT=$RESTART_COUNT
            # Reset phase tracking since we're on a fresh attempt
            PHASE_LEVEL=0
            LAST_PHASE=""
        fi
        
        if [ "$CRASH_DETECTIONS" -ge 2 ]; then
            echo ""
            echo -e "${RED}✗ vLLM is crash-looping (restarted ${RESTART_COUNT} times).${NC}"
            echo ""
            # Extract the actual error from the logs
            ERROR_MSG=$(docker logs "$CONTAINER_NAME" 2>&1 | grep -E "RuntimeError|OutOfMemoryError|CUDA|Error|error" | tail -5)
            if [ -n "$ERROR_MSG" ]; then
                echo -e "${RED}  Error from logs:${NC}"
                echo "$ERROR_MSG" | while IFS= read -r line; do
                    echo -e "  ${YELLOW}${line}${NC}"
                done
                echo ""
            fi
            echo "  Troubleshooting:"
            echo -e "  ${BLUE}docker compose logs inference${NC}  - View full logs"
            echo -e "  Try reducing GPU memory: edit .env and lower MAX_CONTEXT"
            echo -e "  Or try a smaller model: ${BLUE}./init.sh${NC}"
            break
        fi
        
        # Check if API is responding (model fully loaded)
        if curl -s --max-time 2 http://localhost:8000/v1/models > /dev/null 2>&1; then
            echo -e "\n${GREEN}✓ Model loaded and ready!${NC}"
            READY=true
            break
        fi
        
        # Parse the latest vLLM log line to determine startup phase
        # Use --tail 10 to catch log lines that may scroll past quickly
        LAST_LOG=$(docker logs "$CONTAINER_NAME" --tail 10 2>&1)
        CANDIDATE_PHASE=""
        CANDIDATE_LEVEL=0
        DETAIL=""
        
        # Check phases in order of progression (highest priority first)
        if echo "$LAST_LOG" | grep -q "CUDA graphs"; then
            GRAPH_PCT=$(echo "$LAST_LOG" | grep -oE '[0-9]+%\|' | sed 's/|//' | tail -1)
            CANDIDATE_PHASE="Capturing CUDA graphs"
            CANDIDATE_LEVEL=5
            DETAIL="${GRAPH_PCT:-working...}"
        elif echo "$LAST_LOG" | grep -q "torch.compile\|Dynamo bytecode\|compile range"; then
            CANDIDATE_PHASE="Compiling model kernels"
            CANDIDATE_LEVEL=4
            DETAIL="(torch.compile)"
        elif echo "$LAST_LOG" | grep -q "Autotuning"; then
            CANDIDATE_PHASE="Autotuning kernels"
            CANDIDATE_LEVEL=3
            DETAIL=""
        elif echo "$LAST_LOG" | grep -q "Loading safetensors\|Loading weights\|Starting to load model"; then
            SHARD_PCT=$(echo "$LAST_LOG" | grep -oE '[0-9]+% Completed' | tail -1)
            CANDIDATE_PHASE="Loading model weights"
            CANDIDATE_LEVEL=2
            DETAIL="${SHARD_PCT:-starting...}"
        else
            # Fall back to download progress
            # Check full HF cache for this model (blobs can be large, snapshots are symlinks)
            CACHE_SIZE=$(docker exec "$CONTAINER_NAME" du -smc "${HF_CACHE_ROOT}/hub/${HF_CACHE_DIR}/" 2>/dev/null | tail -1 | awk '{print $1}')
            if [ -z "$CACHE_SIZE" ] || [ "$CACHE_SIZE" -eq 0 ] 2>/dev/null; then
                # Try broader search in case HF cache layout differs
                CACHE_SIZE=$(docker exec "$CONTAINER_NAME" du -smc "${HF_CACHE_ROOT}/" 2>/dev/null | tail -1 | awk '{print $1}')
            fi
            if [ -n "$CACHE_SIZE" ] && [ "$CACHE_SIZE" -gt 0 ] 2>/dev/null; then
                CANDIDATE_PHASE="Downloading model"
                CANDIDATE_LEVEL=1
                if [ "$CACHE_SIZE" -ge 1024 ] 2>/dev/null; then
                    CACHE_GB=$(echo "scale=1; $CACHE_SIZE / 1024" | bc 2>/dev/null || echo "$((CACHE_SIZE / 1024))")
                    DETAIL="${CACHE_GB} GB cached"
                else
                    DETAIL="${CACHE_SIZE} MB cached"
                fi
            else
                CANDIDATE_PHASE="Initializing"
                CANDIDATE_LEVEL=0
                DETAIL=""
            fi
        fi
        
        # Only advance phase forward, never regress (prevents oscillation)
        if [ "$CANDIDATE_LEVEL" -ge "$PHASE_LEVEL" ]; then
            # Print newline to preserve the old status line before showing new phase
            if [ "$CANDIDATE_PHASE" != "$LAST_PHASE" ] && [ -n "$LAST_PHASE" ]; then
                echo ""
            fi
            PHASE="$CANDIDATE_PHASE"
            PHASE_LEVEL=$CANDIDATE_LEVEL
            LAST_PHASE="$PHASE"
        else
            PHASE="$LAST_PHASE"
        fi
        
        # Print phase with optional detail (overwrites current line)
        if [ -n "$DETAIL" ]; then
            printf "\r  ⏳ %s... %s   " "$PHASE" "$DETAIL"
        else
            printf "\r  ⏳ %s...           " "$PHASE"
        fi
        
        sleep 3
    done
    echo ""
else
    echo "Run 'docker compose up -d' when ready."
fi
